# Generated by Django 4.1.7 on 2024-06-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('HTML', 'HTML'), ('CSS', 'CSS')], default='python', max_length=100),
        ),
    ]
